package Interface;


import dividedespesa.DivideDespesaFacade;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gomes
 */
public class RegistoII extends javax.swing.JDialog implements Observer {

    private static DivideDespesaFacade facade;
    private static String usernameSenhorio, usernameAdmin, nomeSenhorio, passSenhorio,
                          passAdmin, descApartamento;
    
    /**
     * Creates new form RegistoII
     */
    public RegistoII(java.awt.Frame Registo, boolean modal,
                     DivideDespesaFacade facade, String usernameSenhorio,
                     String usernameAdmin, String nomeSenhorio, String passSenhorio,
                     String passAdmin, String descApartamento) {
        super(Registo, modal);
        initComponents();
        this.facade = facade;
        this.usernameAdmin = usernameAdmin;
        this.usernameSenhorio = usernameSenhorio;
        this.nomeSenhorio = nomeSenhorio;
        this.passSenhorio = passSenhorio;
        this.passAdmin = passAdmin;
        this.descApartamento = descApartamento;
        this.facade.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numQuartos = new javax.swing.JLabel();
        terminaQuartos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        adicionaQuarto = new javax.swing.JButton();
        rendaField = new javax.swing.JTextField();
        removeQuarto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registo(II)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nº Quartos");

        numQuartos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numQuartos.setForeground(new java.awt.Color(102, 0, 0));
        numQuartos.setText("        0");
        numQuartos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                numQuartosComponentShown(evt);
            }
        });

        terminaQuartos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        terminaQuartos.setText("Terminar");
        terminaQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminaQuartosActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Retroceder");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        adicionaQuarto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adicionaQuarto.setText("Adicionar Quarto");
        adicionaQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionaQuartoActionPerformed(evt);
            }
        });

        removeQuarto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        removeQuarto.setText("Remover último");
        removeQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(terminaQuartos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(numQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 161, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rendaField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adicionaQuarto))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(removeQuarto)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numQuartos))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adicionaQuarto)
                    .addComponent(rendaField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeQuarto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(terminaQuartos))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this,"Deseja retroceder?","Confirmaçao",JOptionPane.YES_NO_OPTION);
        if(opcao == 0){
            System.out.print("sim");
            this.dispose();
        }
        else System.out.print("não");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void terminaQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminaQuartosActionPerformed
        
        int opcao = JOptionPane.showConfirmDialog(this,"Deseja Terminar?","Confirmaçao",JOptionPane.YES_NO_OPTION);
        if(opcao == 0){
            
            facade.registaApartamento(usernameSenhorio, usernameAdmin, nomeSenhorio,
                                       passSenhorio, passAdmin, descApartamento);
            
            UserSenhorio dialog = new UserSenhorio(new javax.swing.JFrame(),
                                                   true, facade);
            
            System.gc();
            java.awt.Window win[] = java.awt.Window.getWindows();  
            win[1].dispose(); 
            win[1]=null;
            this.dispose();
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_terminaQuartosActionPerformed

    private void adicionaQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionaQuartoActionPerformed
        String rendaStr = rendaField.getText();
        
        try {
            facade.addToPrecos(rendaStr);

        } catch (NumberFormatException e) {
            String msg = "Introduza um valor válido.";
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_adicionaQuartoActionPerformed

    private void numQuartosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_numQuartosComponentShown

    }//GEN-LAST:event_numQuartosComponentShown

    private void removeQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeQuartoActionPerformed
        try {
            facade.removeQuarto();
        } catch (IndexOutOfBoundsException e) {
            String msg = "Não há quartos para remover.";
            JOptionPane.showMessageDialog(this, msg);
        }

    }//GEN-LAST:event_removeQuartoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistoII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistoII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistoII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistoII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistoII dialog = new RegistoII(new javax.swing.JFrame(), true,
                                                 facade, usernameSenhorio,
                                                 usernameAdmin, nomeSenhorio,
                                                 passSenhorio, passAdmin,
                                                 descApartamento);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionaQuarto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numQuartos;
    private javax.swing.JButton removeQuarto;
    private javax.swing.JTextField rendaField;
    private javax.swing.JButton terminaQuartos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        this.numQuartos.setText(Integer.toString(facade.getNumQuartos()));
    }
}
