package Interface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import dividedespesa.DivideDespesaFacade;
import javax.swing.JOptionPane;

/**
 *
 * @author Gomes
 */
public class UserSenhorio extends javax.swing.JDialog {

    private static DivideDespesaFacade facade;
    
    /**
     * Creates new form UserSenhorio
     */
    public UserSenhorio(java.awt.Frame JanelaInicial, boolean modal,
                        DivideDespesaFacade facade) {
        super(JanelaInicial, modal);
        initComponents();
        this.facade = facade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adicionarMorador = new javax.swing.JButton();
        verDespesas = new javax.swing.JButton();
        removerMorador = new javax.swing.JButton();
        alterarDadosMorador = new javax.swing.JButton();
        alterarRenda = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        cobrarRenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Senhorio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        adicionarMorador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adicionarMorador.setText("Adicionar Morador");
        adicionarMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarMoradorActionPerformed(evt);
            }
        });

        verDespesas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        verDespesas.setText("Ver Despesas");
        verDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDespesasActionPerformed(evt);
            }
        });

        removerMorador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removerMorador.setText("Remover Morador");
        removerMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerMoradorActionPerformed(evt);
            }
        });

        alterarDadosMorador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alterarDadosMorador.setText("Alterar Dados Morador");
        alterarDadosMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosMoradorActionPerformed(evt);
            }
        });

        alterarRenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alterarRenda.setText("Alterar Renda");
        alterarRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarRendaActionPerformed(evt);
            }
        });

        sair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        cobrarRenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cobrarRenda.setText("Cobrar Renda ");
        cobrarRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrarRendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verDespesas)
                            .addComponent(adicionarMorador)
                            .addComponent(removerMorador)
                            .addComponent(alterarDadosMorador)
                            .addComponent(alterarRenda)
                            .addComponent(cobrarRenda))
                        .addGap(0, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adicionarMorador)
                .addGap(18, 18, 18)
                .addComponent(verDespesas)
                .addGap(18, 18, 18)
                .addComponent(removerMorador)
                .addGap(18, 18, 18)
                .addComponent(alterarDadosMorador)
                .addGap(18, 18, 18)
                .addComponent(alterarRenda)
                .addGap(18, 18, 18)
                .addComponent(cobrarRenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sair)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cobrarRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrarRendaActionPerformed
       
        String msg = facade.cobrarRenda(); 
        JOptionPane.showMessageDialog(this, msg);
    }//GEN-LAST:event_cobrarRendaActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
       int opcao = JOptionPane.showConfirmDialog(this,"Deseja Sair?","Confirmação",JOptionPane.YES_NO_OPTION);
       if(opcao == 0){
           System.out.print("sim");
           this.dispose();
       }
       else System.out.print("não");
    }//GEN-LAST:event_sairActionPerformed

    private void adicionarMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarMoradorActionPerformed
        AdicionarMorador dialog = new AdicionarMorador(new javax.swing.JFrame(),
                                                       true, facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_adicionarMoradorActionPerformed

    private void verDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDespesasActionPerformed
        VerDespesas dialog = new VerDespesas(new javax.swing.JFrame(), true, facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_verDespesasActionPerformed

    private void removerMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerMoradorActionPerformed
        RemoverMorador dialog = new RemoverMorador(new javax.swing.JFrame(), true, facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_removerMoradorActionPerformed

    private void alterarDadosMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosMoradorActionPerformed
        AlterarDadosMorador dialog = new AlterarDadosMorador(new javax.swing.JFrame(),
                                                             true, facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_alterarDadosMoradorActionPerformed

    private void alterarRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarRendaActionPerformed
        AlterarRenda dialog = new AlterarRenda(new javax.swing.JFrame(),true, facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_alterarRendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSenhorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSenhorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSenhorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSenhorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserSenhorio dialog = new UserSenhorio(new javax.swing.JFrame(),
                                                       true, facade);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarMorador;
    private javax.swing.JButton alterarDadosMorador;
    private javax.swing.JButton alterarRenda;
    private javax.swing.JButton cobrarRenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton removerMorador;
    private javax.swing.JButton sair;
    private javax.swing.JButton verDespesas;
    // End of variables declaration//GEN-END:variables
}
