package dividedespesa.Interface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import dividedespesa.BusinessLayer.DivideDespesaFacade;
import javax.swing.JOptionPane;


public class Registo extends javax.swing.JDialog {
    
    private static DivideDespesaFacade facade;
    
    /**
     * Creates new form Registo
     */
    public Registo(java.awt.Frame JanelaInicial, boolean modal,
                   DivideDespesaFacade facade) {
        super(JanelaInicial, modal);
        initComponents();
        this.facade = facade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeSenhorioField = new javax.swing.JTextField();
        usernameSenhorioField = new javax.swing.JTextField();
        passwordSenhorioField = new javax.swing.JPasswordField();
        continuarButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usernameAdminField = new javax.swing.JTextField();
        passwordAdminField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("RegistoI"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registar Apartamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText(" Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText(" Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText(" Password");

        nomeSenhorioField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomeSenhorioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeSenhorioFieldActionPerformed(evt);
            }
        });

        usernameSenhorioField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameSenhorioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameSenhorioFieldActionPerformed(evt);
            }
        });

        passwordSenhorioField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordSenhorioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordSenhorioFieldActionPerformed(evt);
            }
        });

        continuarButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        continuarButton.setText("Continuar");
        continuarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Senhorio ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Administrador ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Password");

        usernameAdminField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameAdminField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameAdminFieldActionPerformed(evt);
            }
        });

        passwordAdminField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordAdminField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordAdminFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameSenhorioField)
                                    .addComponent(passwordSenhorioField)
                                    .addComponent(nomeSenhorioField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(continuarButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordAdminField)
                            .addComponent(usernameAdminField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeSenhorioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(usernameSenhorioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordSenhorioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(usernameAdminField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(passwordAdminField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(continuarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int opcao = JOptionPane.showConfirmDialog(this,"Deseja Cancelar Registo?","Confirmação",JOptionPane.YES_NO_OPTION);
       if(opcao == 0){
           this.dispose();
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void continuarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarButtonActionPerformed
        String usernameAdmin = usernameAdminField.getText();
        String usernameSenhorio = usernameSenhorioField.getText();
        String nomeSenhorio = nomeSenhorioField.getText();
        String passSenhorio = String.valueOf(passwordSenhorioField.getPassword());
        String passAdmin = String.valueOf(passwordAdminField.getPassword());
        boolean campos, senhorio, admin;

        if (facade.fieldSize(usernameSenhorio, passSenhorio, nomeSenhorio) || 
            facade.fieldSize(usernameAdmin, passAdmin, "aaa")) {
            campos = false;
            String msgCampos = "Todos os campos têm que estar preenchidos!";
            JOptionPane.showMessageDialog(this, msgCampos);
        } else {
            campos = true;
        }
        
        if (!facade.validaSenhorio(nomeSenhorio, usernameSenhorio, passSenhorio)) {
            senhorio = false;
            String msgSenhorio = "Os dados de login do Senhorio não podem ter carateres especiais!";
            JOptionPane.showMessageDialog(this, msgSenhorio);   
        } else {
            senhorio = true;
        }
        
        if (!facade.validaAdministrador(usernameAdmin, passAdmin)) {
            admin = false;
            String msgAdmin = "Os dados de login do Administrador não podem ter carateres especiais!";
            JOptionPane.showMessageDialog(this, msgAdmin);
        } else {
            admin = true;
        }
        
        if (usernameAdmin.equals(usernameSenhorio)) {
            senhorio = false;
            admin = false;
            String msgAdmin = "O username do Senhorio e do Administrador têm que ser diferentes.";
            JOptionPane.showMessageDialog(this, msgAdmin);
        } 
            
        if (campos && senhorio && admin) {
            RegistoII dialog = new RegistoII(new javax.swing.JFrame(), true,
                                             facade, nomeSenhorio, usernameSenhorio,
                                             passSenhorio, usernameAdmin, passAdmin);
            dialog.setVisible(true);
        }

    }//GEN-LAST:event_continuarButtonActionPerformed

    private void usernameAdminFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameAdminFieldActionPerformed

    }//GEN-LAST:event_usernameAdminFieldActionPerformed

    private void nomeSenhorioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeSenhorioFieldActionPerformed

    }//GEN-LAST:event_nomeSenhorioFieldActionPerformed

    private void passwordSenhorioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordSenhorioFieldActionPerformed

    }//GEN-LAST:event_passwordSenhorioFieldActionPerformed

    private void usernameSenhorioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameSenhorioFieldActionPerformed

    }//GEN-LAST:event_usernameSenhorioFieldActionPerformed

    private void passwordAdminFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordAdminFieldActionPerformed

    }//GEN-LAST:event_passwordAdminFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeSenhorioField;
    private javax.swing.JPasswordField passwordAdminField;
    private javax.swing.JPasswordField passwordSenhorioField;
    private javax.swing.JTextField usernameAdminField;
    private javax.swing.JTextField usernameSenhorioField;
    // End of variables declaration//GEN-END:variables
}
