package dividedespesa.presentation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import dividedespesa.business.DivideDespesaFacade;
import javax.swing.JOptionPane;


public class UserSenhorio extends javax.swing.JDialog {

    private static DivideDespesaFacade facade;
    
    /**
     * Creates new form UserSenhorio
     */
    public UserSenhorio(java.awt.Frame JanelaInicial, boolean modal,
                        DivideDespesaFacade facade) {
        super(JanelaInicial, modal);
        initComponents();
        this.facade = facade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adicionarMorador = new javax.swing.JButton();
        verDespesas = new javax.swing.JButton();
        removerMorador = new javax.swing.JButton();
        alterarDadosMorador = new javax.swing.JButton();
        alterarRenda = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        cobrarRenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Senhorio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        adicionarMorador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adicionarMorador.setText("Adicionar Morador");
        adicionarMorador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adicionarMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarMoradorActionPerformed(evt);
            }
        });

        verDespesas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        verDespesas.setText("Ver Despesas");
        verDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDespesasActionPerformed(evt);
            }
        });

        removerMorador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removerMorador.setText("Remover Morador");
        removerMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerMoradorActionPerformed(evt);
            }
        });

        alterarDadosMorador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alterarDadosMorador.setText("Alterar Dados Morador");
        alterarDadosMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosMoradorActionPerformed(evt);
            }
        });

        alterarRenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alterarRenda.setText("Alterar Renda");
        alterarRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarRendaActionPerformed(evt);
            }
        });

        sair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        cobrarRenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cobrarRenda.setText("Cobrar Renda ");
        cobrarRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrarRendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cobrarRenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alterarRenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removerMorador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adicionarMorador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alterarDadosMorador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addComponent(sair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(adicionarMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removerMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarDadosMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cobrarRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cobrarRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrarRendaActionPerformed
        CobraRenda dialog = new CobraRenda(new javax.swing.JFrame(), true,
                                           facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_cobrarRendaActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
       int opcao = JOptionPane.showConfirmDialog(this,"Deseja Sair?","Confirmação",JOptionPane.YES_NO_OPTION);

       if(opcao == 0){
           this.dispose();
       }
    }//GEN-LAST:event_sairActionPerformed

    private void adicionarMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarMoradorActionPerformed
        AdicionarMorador dialog = new AdicionarMorador(new javax.swing.JFrame(),
                                                       true, facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_adicionarMoradorActionPerformed

    private void verDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDespesasActionPerformed
        VerDespesas dialog = new VerDespesas(new javax.swing.JFrame(), true, facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_verDespesasActionPerformed

    private void removerMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerMoradorActionPerformed
        RemoverMorador dialog = new RemoverMorador(new javax.swing.JFrame(), true, facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_removerMoradorActionPerformed

    private void alterarDadosMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosMoradorActionPerformed
        AlterarDadosMorador dialog = new AlterarDadosMorador(new javax.swing.JFrame(),
                                                             true, facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_alterarDadosMoradorActionPerformed

    private void alterarRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarRendaActionPerformed
        AlterarRenda dialog = new AlterarRenda(new javax.swing.JFrame(),true, facade);
        dialog.setVisible(true);
    }//GEN-LAST:event_alterarRendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarMorador;
    private javax.swing.JButton alterarDadosMorador;
    private javax.swing.JButton alterarRenda;
    private javax.swing.JButton cobrarRenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton removerMorador;
    private javax.swing.JButton sair;
    private javax.swing.JButton verDespesas;
    // End of variables declaration//GEN-END:variables
}
